export const SET_DATA_TO_CHANGE = "SET_DATA_TO_CHANGE";
export const SET_DATA_TO_CHANGE_LOADING = "SET_DATA_TO_CHANGE_LOADING";
export const SET_DATA_TO_CHANGE_REQUEST_ERROR = "SET_DATA_TO_CHANGE_REQUEST_ERROR";
export const GET_DATA_TO_CHANGE = "GET_DATA_TO_CHANGE";
export const SET_DATA_TO_CHANGE_ROUTE_NAME = "SET_DATA_TO_CHANGE_ROUTE_NAME";