export const SET_ORDER_DATA = "SET_ORDER_DATA";
export const GET_ORDER_DATA = "GET_ORDER_DATA";
export const SET_ORDER_DATA_LOADING = "SET_ORDER_DATA_LOADING";
export const SET_ORDER_DATA_ERROR = "SET_ORDER_DATA_ERROR";
export const SET_ORDER_PAGINATION = "SET_ORDER_PAGINATION";
export const SET_ORDER_CITY_FILTER = "SET_ORDER_CITY_FILTER";
export const SET_ORDER_CAR_FILTER = "SET_ORDER_CAR_FILTER";
export const SET_ORDER_POINT_FILTER = "SET_ORDER_POINT_FILTER";