export const SET_ORDER_DATA = "SET_ORDER_DATA";
export const GET_ORDER_DATA = "GET_ORDER_DATA";
export const SET_ORDER_DATA_LOADING = "SET_ORDER_DATA_LOADING";
export const SET_ORDER_DATA_ERROR = "SET_ORDER_DATA_ERROR";