export const SET_ORDER_DATA = "SET_ORDER_DATA";
export const GET_ORDER_DATA = "GET_ORDER_DATA";
export const SET_ORDER_DATA_LOADING = "SET_ORDER_DATA_LOADING";
export const SET_ORDER_DATA_ERROR = "SET_ORDER_DATA_ERROR";
export const SET_ORDER_PAGINATION = "SET_ORDER_PAGINATION";

export const SET_ORDER_CITY_FILTER = "SET_ORDER_CITY_FILTER";
export const SET_ORDER_CAR_FILTER = "SET_ORDER_CAR_FILTER";
export const SET_ORDER_POINT_FILTER = "SET_ORDER_POINT_FILTER";

export const SET_TABLE_CARS_DATA = "SET_TABLE_CARS_DATA";
export const SET_TABLE_CARS_PAGINATION = "SET_TABLE_CARS_PAGINATION";
export const SET_TABLE_CARS_DATA_LOADING = "SET_TABLE_CARS_DATA_LOADING";
export const SET_TABLE_CARS_REQUEST_ERROR = "SET_TABLE_CARS_DATA_ERROR";
export const SET_TABLE_CARS_FILTER = "SET_TABLE_CARS_FILTER";
export const GET_TABLE_CARS_DATA = "GET_TABLE_CARS_DATA";
export const SET_TABLE_CAR_BY_ID_DATA = "SET_TABLE_CAR_BY_ID_DATA";
export const SET_TABLE_CAR_BY_ID_LOADING = "SET_TABLE_CAR_BY_ID_LOADING";
export const SET_TABLE_CAR_BY_ID_REQUEST_ERROR = "SET_TABLE_CAR_BY_ID_REQUEST_ERROR";
export const GET_TABLE_CAR_BY_ID_DATA = "GET_TABLE_CAR_BY_ID_DATA";

export const SET_TABLE_CITIES_DATA = "SET_TABLE_CITIES_DATA";
export const SET_TABLE_CITIES_DATA_LOADING = "SET_TABLE_CITIES_DATA_LOADING";
export const SET_TABLE_CITIES_REQUEST_ERROR = "SET_TABLE_CITIES_REQUEST_ERROR";
export const GET_TABLE_CITIES_DATA = "GET_TABLE_CITIES_DATA";
export const SET_TABLE_CITIES_PAGINATION = "SET_TABLE_CITIES_PAGINATION";

export const SET_TABLE_POINT_DATA = "SET_TABLE_POINT_DATA";
export const SET_TABLE_POINT_DATA_LOADING = "SET_TABLE_POINT_DATA_LOADING";
export const SET_TABLE_POINT_REQUEST_ERROR = "SET_TABLE_POINT_REQUEST_ERROR";
export const SET_TABLE_POINT_PAGINATION = "SET_TABLE_POINT_PAGINATION";
export const GET_TABLE_POINT_DATA = "GET_TABLE_POINT_DATA";

export const SET_TABLE_RATETYPES_DATA = "SET_TABLE_RATETYPES_DATA";
export const SET_TABLE_RATETYPES_DATA_LOADING = "SET_TABLE_RATETYPES_DATA_LOADING";
export const SET_TABLE_RATETYPES_REQUEST_ERROR = "SET_TABLE_RATETYPES_REQUEST_ERROR";
export const SET_TABLE_RATETYPES_PAGINATION = "SET_TABLE_RATETYPES_PAGINATION";
export const GET_TABLE_RATETYPES_DATA = "GET_TABLE_RATETYPES_DATA";