export const SET_USER_LOGIN_DATA = "SET_USER_LOGIN_DATA";
export const SET_USER_LOGIN_LOADING = "SET_USER_LOGIN_LOADING";
export const SET_USER_LOGIN_ERROR = "SET_USER_LOGIN_ERROR";
export const LOGIN_USER = "LOGIN_USER";
export const REFRESH_USER = "REFRESH_USER";
export const AUTHORIZATION_USER_REQUEST_LOADED = "AUTHORIZATION_USER_REQUEST_LOADED";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAR_USER_AUTH_DATA = "CLEAR_USER_AUTH_DATA";