export const SET_USER_LOGIN_DATA = "SET_USER_LOGIN_DATA";
export const SET_USER_LOGIN_LOADING = "SET_USER_LOGIN_LOADING";
export const SET_USER_LOGIN_ERROR = "SET_USER_LOGIN_ERROR";
export const LOGIN_USER = "LOGIN_USER";